name: Pull Request to Develop

on:
  pull_request:
    branches: [ develop ]

jobs:
  validate_pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
        mkdir ~/sfdx
        tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
        echo "$HOME/sfdx/bin" >> $GITHUB_PATH
        ~/sfdx/bin/sfdx version

    - name: Install jq
      run: |
        sudo apt-get install jq
    
    - name: Populate auth file
      shell: bash
      run: 'echo ${{secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'
    
    - name: Authenticate Dev Hub
      run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'

    - name: Create scratch org
      run: 'sf org create scratch -f config/project-scratch-def.json -a ci_scratch -y 1'
    
    - name: Push source to scratch org
      run: 'sfdx force:source:push -o ci_scratch'
    
    - name: Check code coverage
      run:  |
            'sf apex test run --code-coverage --result-format human --synchronous -o ci_scratch --test-level RunLocalTests --wait 10' 
            if [ "$code_coverage" -lt "$required_coverage" ]; 
            then
            echo "Failed due to less code coverage. Current coverage: $code_coverage%"
            exit 1
            else
            echo "Code coverage is sufficient. Current coverage: $code_coverage%"
            exit 0
            fi

    - name: Delete scratch org
      if: always()
      run: 'sf org delete scratch -p -o ci_scratch'
